apiVersion: v1
kind: ConfigMap
metadata:
  name: egov-global-config
data:
  # 기본 데이터 경로
  data_base_path: "/mnt/host/c/Users/comgh/egovframe-common-components-msa-krds/k8s-deploy/data"
  
  # EgovMobileId 설정 경로
  mobileid_config_path: "/mnt/host/c/Users/comgh/egovframe-common-components-msa-krds/EgovMobileId/config"
  
  # EgovSearch 관련 경로
  search_base_path: "/mnt/host/c/Users/comgh/egovframe-common-components-msa-krds/EgovSearch-config"
