apiVersion: apps/v1
kind: Deployment
metadata:
  name: egov-hello-error
  namespace: egov-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egov-hello
      variant: error
  template:
    metadata:
      labels:
        app: egov-hello
        variant: error
        version: "v4.3.0"
    spec:
      containers:
      - name: egov-hello
        image: egovframe/egovhello:4.3.0.k8s
        imagePullPolicy: Always #IfNotPresent : Downloads the image only if it does not exist on the node
        ports:
        - containerPort: 80
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SERVER_PORT
          value: "80"
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: "false"
        - name: SPRING_CLOUD_DISCOVERY_ENABLED
          value: "false"
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.egov-monitoring.svc.cluster.local:4317"
        - name: FORCE_ERROR
          value: "true"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3