apiVersion: apps/v1
kind: Deployment
metadata:
  name: egov-search
  namespace: egov-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egov-search
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: egov-search
        version: "v4.3.2"
    spec:
      containers:
      - name: egov-search
        image: egovframe/egovsearch:4.3.2.k8s
        imagePullPolicy: Always #IfNotPresent : Downloads the image only if it does not exist on the node
        ports:
        - containerPort: 80
        #resources:
        #  requests:
        #    cpu: "500m"
        #    memory: "4096Mi"
        #  limits:
        #    cpu: "500m"
        #    memory: "4096Mi"
        envFrom:
        - configMapRef:
            name: egov-common-config
        - secretRef:
            name: mysql-secret
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SERVER_PORT
          value: "80"
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: "false"
        - name: SPRING_CLOUD_DISCOVERY_ENABLED
          value: "false"
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
        - name: APP_SEARCH_CONFIG_PATH
          value: "/app/config/searchConfig-docker.json"
        - name: OPENSEARCH_KEYSTORE_PATH
          value: "/app/cacerts/cacerts.opensearch"
        - name: OPENSEARCH_KEYSTORE_PASSWORD
          value: "egov1234!"
        - name: OPENSEARCH_PROTOCOL
          value: "https"  # https에서 http로 변경
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          value: "admin"
        - name: OPENSEARCH_PASSWORD
          value: "admin"
        - name: OPENSEARCH_URL
          value: "opensearch-0.opensearch-headless.egov-db.svc.cluster.local"  # 내부 서비스 주소 사용
        - name: OPENSEARCH_PORT
          value: "9200"
        - name: LOGGING_LEVEL_EGOVFRAMEWORK_COM_EXT_OPS
          value: "DEBUG"
        - name: LOGGING_LEVEL_ORG_OPENSEARCH
          value: "DEBUG"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq.egov-infra.svc.cluster.local"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "guest"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "guest"
        - name: APP_OPENAPI_SERVER_URL
          value: "http://localhost:30992"
        volumeMounts:
        - name: search-config-shared
          mountPath: /app/config
          subPath: config
          readOnly: true
        - name: search-config-shared
          mountPath: /app/model
          subPath: model
        - name: search-config-shared
          mountPath: /app/cacerts
          subPath: cacerts
          readOnly: true
        - name: search-config-shared
          mountPath: /app/example
          subPath: example
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
      volumes:
      - name: search-config-shared
        persistentVolumeClaim:
          # To use Local Path storage, uncomment this and comment out the NFS claim
          # Using NFS storage
          claimName: egov-search-config-pvc-nfs
          # Using Local Path storage
          #claimName: egov-search-config-pvc-local
---
apiVersion: v1
kind: Service
metadata:
  name: egov-search
  namespace: egov-app
spec:
  selector:
    app: egov-search
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30992
  type: NodePort
