apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  labels:
    env: production
    tier: storage
    app: nfs
    name: nfs
provisioner: nfs-provisioner
#reclaimPolicy: Retain # 삭제하지 않고 유지
parameters:
  archiveOnDelete: "false"